# Generated by Django 3.2.6 on 2021-08-20 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('description', models.TextField(verbose_name='Описание')),
                ('event_date', models.DateField(verbose_name='Дата')),
                ('event_time', models.TimeField(null=True, verbose_name='Время')),
                ('pictures', models.ImageField(null=True, upload_to='event_pictures/', verbose_name='Картинки')),
                ('active', models.CharField(choices=[('1', 'Интересно'), ('2', 'Пойду'), ('3', 'Не пойду')], default=True, max_length=20, verbose_name='Ваш ответ')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.SmallIntegerField(verbose_name='Количество звезд')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ratings', to='events.event')),
            ],
            options={
                'verbose_name': 'Рейтинг мероприятия',
                'verbose_name_plural': 'Рейтинги мероприятий',
            },
        ),
    ]
